spring.application.name=tennis-ladder

spring.datasource.url=jdbc:postgresql://localhost:53432/tennis-ladder
spring.datasource.username=${POSTGRES_USER:postgres}
spring.datasource.password=${POSTGRES_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver